### PR TITLE
Massive overhaul of Display.js and GUI editor

### PR DESCRIPTION
**Pull request by dalcde**
See commit messages for details. Many examples are still broken so probably best to leave this open until I get around to fixing them. Sample of editor can be found at https://dec41.user.srcf.net/tmp/ss/

### CODE REVIEW

**Comment by dalcde** [comment]
AFAIK all examples should be working now apart from ui.js. Some specific interactive functionality might not have been tested thoroughly.

**Comment by dalcde** [comment]
I messed around with ExportToTex.js a bit to make it render things a bit more nicely. It currently only supports very basic node/edge properties and my current intention is to add more features as they are needed.

**Comment by hoodmane** [comment]
It's my intention to set up an unchecked interface to the latex package --
it takes a long time for it to compile, and much of that time is spent on
input parsing and verification. However, I imagine a common use case is
going to be to produce diagrams using other programs. I think exporting
through my package is a good idea so that the user can make manual
adjustments in a separate file from the generated code. There is obvious
merit to the export to svg approach that we already have. A low-level pgf
approach would produce faster compiling documents, but is slower than
importing an svg and provides none of the flexibility of the package. The
only advantage of the pgf approach is for font compatibility. Speaking of
which, do you know whether it's possible to use the latex fonts in an svg?

**Comment by dalcde** [comment]
I'm not aware of a decent way to use LaTeX fonts in an svg. If you do things by hand, Inkscape can produce PDF + LaTeX output from an svg that renders the text using LaTeX. Regardless, position of text can become tricky.

One advantage of using the LaTeX spectralsequence package is that it will behave well with scaling.

**Comment by dalcde** [comment]
The intent of the latest commit is so that users can specify customization of the spectral sequence outside of the generated file. The intended use case is that the user directly `\input`s the generated tex file into their document, and does the customization in the main document (specifically, with this commit, the user can write, e.g.
```
\def\sseqscale{0.5}
\input{S_2.tex}
```
to display a half-sized spectral sequence). This way if the user modifies the spectral sequence and generates a new tex file, they wouldn't have to re-do all the customization again.

The current code is definitely suboptimal. For one, one would want to be able to perform other customizations (e.g. grids and ticks). I am bad at LaTeX and have not managed to figure out how to make LaTeX do this. The following code results in an error when sseqoption is defined:
```
\def\sseqoptions{scale = 0.5}
\begin{sseqpage}[degree = {-1}{#1}, x range = {0}{10}, y range = {0}{10}, \sseqoptions]
```

One way to solve this problem is to make the generated code provide `sseqdata` only, and the user has to manually `\printpage`. This would requiring giving names to the `sseqdata` generated, e.g. `sseq.name + " " + page`.

**Comment by hoodmane** [comment]
To get that code to work you should say:

\makeatletter
\def\sseqoptions{scale = 0.5}
\sseq@eval{ \@nx\begin{sseqpage}[degree = {-1}{#1}, x range = {0}{10}, y
range = {0}{10}, \sseqoptions]}
\makeatother

Though there are several better alternatives. For instance you could say
\begingroup
\sseqset{scale = 0.5}
\begin{sseqpage}[degree = {-1}{#1}, x range = {0}{10}, y range = {0}{10}]
...
\end{sseqpage}
\endgroup

The intended way to deal with this though is that you put the content of
the spectral sequence in a sseqdata environment and then use
\printpage[name=sseqname,
<...options>] or even
\begin{sseqdata}[name=sseqname, update existing, <... options>]
\end{sseqdata}

**Comment by hoodmane** [comment]
To get that code to work you should say:

```
    \makeatletter
    \def\sseqoptions{scale = 0.5}
    \sseq@eval{ \@nx\begin{sseqpage}[degree = {-1}{#1}, x range = {0}{10}, y range = {0}{10}, \sseqoptions]}
    \makeatother
```

Though there are several better alternatives. For instance you could say
```
    \begingroup
    \sseqset{scale = 0.5}
    \begin{sseqpage}[degree = {-1}{#1}, x range = {0}{10}, y range = {0}{10}]
    ...
    \end{sseqpage}
    \endgroup
```

The intended way to deal with this though is that you put the content of
the spectral sequence in a sseqdata environment and then use
`\printpage[name=sseqname,<...options>]` or even

```
    \begin{sseqdata}[name=sseqname, update existing, <... options>]
    \end{sseqdata}
```
In fact, this use case was one of the main design reasons for having a separate "sseqdata" environment.

**Pull request merged**
