### PR TITLE
Changes for rust_ext

### PR DESCRIPTION
**Pull request by dalcde**

### CODE REVIEW

**Comment by dalcde** [comment]
This is required by https://github.com/hoodmane/rust_ext/commit/93d5e02604adce01421b042654cb7677feb2c0fa

**Comment by hoodmane** [comment]
Does this fix the tooltips glitch?

**Comment by dalcde** [comment]
It fixes *some* tooltips glitch. What exactly are you thinking about?

**Comment by hoodmane** [comment]
Tooltip region was displaced from the displayed class.

**Comment by hoodmane** [comment]
You seem to have fixed it, regardless of whether this was the fix. Danny was hassling me about it so I'm glad it works again.

**Pull request merged**
